//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Views.TextView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Views.TextView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap login_16 {
            get {
                object obj = ResourceManager.GetObject("login_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu file thành công!
        ///Bạn có muốn mở file không?.
        /// </summary>
        internal static string Message_ExportSuccess {
            get {
                return ResourceManager.GetString("Message_ExportSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file để lưu.
        /// </summary>
        internal static string TextViewForm_ChoiseFileToSave {
            get {
                return ResourceManager.GetString("TextViewForm_ChoiseFileToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tính toán.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_CalcValue {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_CalcValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Clear {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Edit {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_File {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_FromDate {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Group {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_GroupName {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_LoggerName {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_LoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture View.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Picture_View {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Picture_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_PictureName {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_PictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thô.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_RawValue {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_RawValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_SensorName {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_SensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Sensors {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text View.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_Title {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_ToDate {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_View {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem theo tùy chọn.
        /// </summary>
        internal static string TextViewForm_InitializeComponent_ViewByOption {
            get {
                return ResourceManager.GetString("TextViewForm_InitializeComponent_ViewByOption", resourceCulture);
            }
        }
    }
}
