//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Views.PictureView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Views.PictureView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa hình ảnh này không?.
        /// </summary>
        internal static string Confirm_DeletePictureView {
            get {
                return ResourceManager.GetString("Confirm_DeletePictureView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_16 {
            get {
                object obj = ResourceManager.GetObject("disk_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết tới: .
        /// </summary>
        internal static string EditGroupIndicatorForm_Current_Values {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Current_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cao.
        /// </summary>
        internal static string EditGroupIndicatorForm_Height {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lề trái.
        /// </summary>
        internal static string EditGroupIndicatorForm_Left {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn hình ảnh.
        /// </summary>
        internal static string EditGroupIndicatorForm_PictureViewTab {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_PictureViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string EditGroupIndicatorForm_Position {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string EditGroupIndicatorForm_Save {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        internal static string EditGroupIndicatorForm_Size {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đối tượng.
        /// </summary>
        internal static string EditGroupIndicatorForm_Title {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lề trên.
        /// </summary>
        internal static string EditGroupIndicatorForm_Top {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rộng.
        /// </summary>
        internal static string EditGroupIndicatorForm_Width {
            get {
                return ResourceManager.GetString("EditGroupIndicatorForm_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị: .
        /// </summary>
        internal static string EditObjectForm_Current_Value {
            get {
                return ResourceManager.GetString("EditObjectForm_Current_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến đang chọn:.
        /// </summary>
        internal static string EditObjectForm_CurrentSensor {
            get {
                return ResourceManager.GetString("EditObjectForm_CurrentSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cao.
        /// </summary>
        internal static string EditObjectForm_Height {
            get {
                return ResourceManager.GetString("EditObjectForm_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lề trái.
        /// </summary>
        internal static string EditObjectForm_Left {
            get {
                return ResourceManager.GetString("EditObjectForm_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí, kích thước.
        /// </summary>
        internal static string EditObjectForm_Position {
            get {
                return ResourceManager.GetString("EditObjectForm_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string EditObjectForm_PostionLabel {
            get {
                return ResourceManager.GetString("EditObjectForm_PostionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string EditObjectForm_Save {
            get {
                return ResourceManager.GetString("EditObjectForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Cảm biến hiển thị.
        /// </summary>
        internal static string EditObjectForm_SelectSensor {
            get {
                return ResourceManager.GetString("EditObjectForm_SelectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        internal static string EditObjectForm_Size {
            get {
                return ResourceManager.GetString("EditObjectForm_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đối tượng.
        /// </summary>
        internal static string EditObjectForm_Title {
            get {
                return ResourceManager.GetString("EditObjectForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lề trên.
        /// </summary>
        internal static string EditObjectForm_Top {
            get {
                return ResourceManager.GetString("EditObjectForm_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rộng.
        /// </summary>
        internal static string EditObjectForm_Width {
            get {
                return ResourceManager.GetString("EditObjectForm_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gaugeIcon {
            get {
                object obj = ResourceManager.GetObject("gaugeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap groupIndicatorIcon {
            get {
                object obj = ResourceManager.GetObject("groupIndicatorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap horizontalBarIcon {
            get {
                object obj = ResourceManager.GetObject("horizontalBarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imageIcon {
            get {
                object obj = ResourceManager.GetObject("imageIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap indicatorIcon {
            get {
                object obj = ResourceManager.GetObject("indicatorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_16 {
            get {
                object obj = ResourceManager.GetObject("login_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hình ảnh thành công.
        /// </summary>
        internal static string Message_AddPictureViewSuccess {
            get {
                return ResourceManager.GetString("Message_AddPictureViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công!.
        /// </summary>
        internal static string Message_DeletePcitureViewSuccess {
            get {
                return ResourceManager.GetString("Message_DeletePcitureViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        internal static string Message_EditPictureViewSuccess {
            get {
                return ResourceManager.GetString("Message_EditPictureViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meterIcon {
            get {
                object obj = ResourceManager.GetObject("meterIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap numericIndicatorIcon {
            get {
                object obj = ResourceManager.GetObject("numericIndicatorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string PictureInformationForm_IDescription {
            get {
                return ResourceManager.GetString("PictureInformationForm_IDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string PictureInformationForm_IName {
            get {
                return ResourceManager.GetString("PictureInformationForm_IName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string PictureInformationForm_Save {
            get {
                return ResourceManager.GetString("PictureInformationForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hình ảnh.
        /// </summary>
        internal static string PictureInformationForm_Title {
            get {
                return ResourceManager.GetString("PictureInformationForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chỉnh xem.
        /// </summary>
        internal static string PictureViewDetailForm_InitializeComponent_View {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_InitializeComponent_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bản In.
        /// </summary>
        internal static string PictureViewDetailForm_Menu__Print_Preview {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu__Print_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm....
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Add {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_AddImage {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đưa lên trước.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Bring_To_Front {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Bring_To_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem biểu đồ tương ứng.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Chart_View {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Chart_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng lại.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Close {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_DeleteObject {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Edit {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_EditObject {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_EditObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Exit {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_File {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang đo tròn.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Gauge {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm cảm biến.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Group_Indicator {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Group_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang đo ngang.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Horizontal_Bar {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Horizontal_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Indicator {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang đo.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Meter {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng hồ số.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Numeric_Indicator {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Numeric_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem hình ảnh  tương ứng.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Picture_View {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Picture_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Print {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển sang chế độ chỉnh sửa.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Switch_to_Edit_Mode {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Switch_to_Edit_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem dữ liệu tương ứng.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Text_View {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Text_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang đo dọc.
        /// </summary>
        internal static string PictureViewDetailForm_Menu_Vertical_Bar {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Menu_Vertical_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn một ảnh....
        /// </summary>
        internal static string PictureViewDetailForm_Select_an_image {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Select_an_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển sang chế độ chỉnh sửa.
        /// </summary>
        internal static string PictureViewDetailForm_SwichToEditMode {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_SwichToEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển sang chế độ xem.
        /// </summary>
        internal static string PictureViewDetailForm_SwichToViewMode {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_SwichToViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem theo giá tính toán.
        /// </summary>
        internal static string PictureViewDetailForm_swichValueMode_Calc {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_swichValueMode_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem theo giá trị thô.
        /// </summary>
        internal static string PictureViewDetailForm_swichValueMode_Raw {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_swichValueMode_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem hình ảnh.
        /// </summary>
        internal static string PictureViewDetailForm_Title {
            get {
                return ResourceManager.GetString("PictureViewDetailForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm / Sửa hình ảnh.
        /// </summary>
        internal static string PictureViewsManagerForm_AddEdit {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string PictureViewsManagerForm_Delete {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mô tả.
        /// </summary>
        internal static string PictureViewsManagerForm_Description {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string PictureViewsManagerForm_Edit {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin.
        /// </summary>
        internal static string PictureViewsManagerForm_Edit_Information {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Edit_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string PictureViewsManagerForm_Name {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string PictureViewsManagerForm_New_Picture {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_New_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại bảng.
        /// </summary>
        internal static string PictureViewsManagerForm_RefreshTable {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string PictureViewsManagerForm_save {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hình ảnh.
        /// </summary>
        internal static string PictureViewsManagerForm_Title {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem ảnh.
        /// </summary>
        internal static string PictureViewsManagerForm_vIEW {
            get {
                return ResourceManager.GetString("PictureViewsManagerForm_vIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_edit_16 {
            get {
                object obj = ResourceManager.GetObject("table_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verticalBarIcon {
            get {
                object obj = ResourceManager.GetObject("verticalBarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có hình ảnh nào được chọn!.
        /// </summary>
        internal static string Warning_NoRecordSelected {
            get {
                return ResourceManager.GetString("Warning_NoRecordSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để hiển thị!.
        /// </summary>
        internal static string Warning_NotDataToDisplay {
            get {
                return ResourceManager.GetString("Warning_NotDataToDisplay", resourceCulture);
            }
        }
    }
}
