//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoDIV v1.1.
        /// </summary>
        internal static string AboutForm_Title {
            get {
                return ResourceManager.GetString("AboutForm_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap alarm_red_32 {
            get {
                object obj = ResourceManager.GetObject("alarm_red_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alarm_red_64 {
            get {
                object obj = ResourceManager.GetObject("alarm_red_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_view_32 {
            get {
                object obj = ResourceManager.GetObject("chart_view_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn tắt hoàn chương trình GeoDIV không?.
        /// </summary>
        internal static string Confirm_Exit {
            get {
                return ResourceManager.GetString("Confirm_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại.
        /// </summary>
        internal static string Error_Account_Exist {
            get {
                return ResourceManager.GetString("Error_Account_Exist", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GeoDiv {
            get {
                object obj = ResourceManager.GetObject("GeoDiv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GeoDiv1 {
            get {
                object obj = ResourceManager.GetObject("GeoDiv1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geoviewer {
            get {
                object obj = ResourceManager.GetObject("geoviewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geoviewer1 {
            get {
                object obj = ResourceManager.GetObject("geoviewer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geoviewer2 {
            get {
                object obj = ResourceManager.GetObject("geoviewer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geoviewer21 {
            get {
                object obj = ResourceManager.GetObject("geoviewer21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login_16 {
            get {
                object obj = ResourceManager.GetObject("login_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo lỗi.
        /// </summary>
        internal static string LoginForm_MessageTitle {
            get {
                return ResourceManager.GetString("LoginForm_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2012 - PFIEV Tin học công nghiệp, Đại học Bách Khoa Hà Nội  .
        /// </summary>
        internal static string MainForm_Copyright {
            get {
                return ResourceManager.GetString("MainForm_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string MainForm_MenuItem_Account {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tài khoản.
        /// </summary>
        internal static string MainForm_MenuItem_AccountManager {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_AccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string MainForm_MenuItem_Alarm {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử cảnh báo.
        /// </summary>
        internal static string MainForm_MenuItem_Alarm_Logs {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Alarm_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu, phục hồi dữ liệu.
        /// </summary>
        internal static string MainForm_MenuItem_Backup {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem biểu đồ.
        /// </summary>
        internal static string MainForm_MenuItem_Chart_Views {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Chart_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        internal static string MainForm_MenuItem_Data {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát GeoDIV.
        /// </summary>
        internal static string MainForm_MenuItem_Exit {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn dữ liệu, Cảm biến.
        /// </summary>
        internal static string MainForm_MenuItem_LoggerSensor {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_LoggerSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string MainForm_MenuItem_Logout {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string MainForm_MenuItem_Logout_Help {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Logout_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của tôi.
        /// </summary>
        internal static string MainForm_MenuItem_MyAccount {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem ảnh.
        /// </summary>
        internal static string MainForm_MenuItem_Picture_Views {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_Picture_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem dữ liệu.
        /// </summary>
        internal static string MainForm_MenuItem_TextView {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan sát.
        /// </summary>
        internal static string MainForm_MenuItem_View {
            get {
                return ResourceManager.GetString("MainForm_MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoDIV v1.1.
        /// </summary>
        internal static string MainForm_NotifyIcon_Title {
            get {
                return ResourceManager.GetString("MainForm_NotifyIcon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoDIV v1.1.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoDIV v1.1 - Dự án: {0}.
        /// </summary>
        internal static string MainForm_Title_Project {
            get {
                return ResourceManager.GetString("MainForm_Title_Project", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap man_16 {
            get {
                object obj = ResourceManager.GetObject("man_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap picture_view_32 {
            get {
                object obj = ResourceManager.GetObject("picture_view_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap question_blue_16 {
            get {
                object obj = ResourceManager.GetObject("question_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_view_32 {
            get {
                object obj = ResourceManager.GetObject("text_view_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
