//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm / Chỉnh sửa.
        /// </summary>
        internal static string Add_Edit {
            get {
                return ResourceManager.GetString("Add_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Lưu.
        /// </summary>
        internal static string BackupRestoreForm_Backup {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu toàn bộ dữ liệu ra file backup đặt trong thư mục đã chọn.
        /// </summary>
        internal static string BackupRestoreForm_Backup_Hint {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Backup_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục sao lưu dữ liệu.
        /// </summary>
        internal static string BackupRestoreForm_BackupLabel {
            get {
                return ResourceManager.GetString("BackupRestoreForm_BackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string BackupRestoreForm_Column_CreationDate {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Column_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string BackupRestoreForm_Column_Path {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Column_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước file.
        /// </summary>
        internal static string BackupRestoreForm_Column_Size {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Column_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa file backup lựa chọn.
        /// </summary>
        internal static string BackupRestoreForm_Delete_Hint {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục Hồi.
        /// </summary>
        internal static string BackupRestoreForm_Restore {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi toàn bộ dữ liệu từ file backup đã chọn.
        /// </summary>
        internal static string BackupRestoreForm_Restore_Hint {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Restore_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file phục hồi.
        /// </summary>
        internal static string BackupRestoreForm_RestoreLabel {
            get {
                return ResourceManager.GetString("BackupRestoreForm_RestoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string BackupRestoreForm_Select {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu phục hồi dữ liệu.
        /// </summary>
        internal static string BackupRestoreForm_Title {
            get {
                return ResourceManager.GetString("BackupRestoreForm_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap calculator_16 {
            get {
                object obj = ResourceManager.GetObject("calculator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn....
        /// </summary>
        internal static string Choise {
            get {
                return ResourceManager.GetString("Choise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn tính toán lại giá trị {0} cảm biến đã chọn không?.
        /// </summary>
        internal static string Confirm_CalculateSensors {
            get {
                return ResourceManager.GetString("Confirm_CalculateSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa file backup {0} không?.
        /// </summary>
        internal static string Confirm_DeleteBackup {
            get {
                return ResourceManager.GetString("Confirm_DeleteBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có xóa {0} cảm biến đã chọn không?.
        /// </summary>
        internal static string Confirm_DeleteSensors {
            get {
                return ResourceManager.GetString("Confirm_DeleteSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn phục hồi toàn bộ dữ liệu từ file {0} không?.
        /// </summary>
        internal static string Confirm_Restore {
            get {
                return ResourceManager.GetString("Confirm_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các cảm biến trong logger này chưa được nhập hết tham số tính toán, do đó khi tiến hành đọc dữ liệu thô hệ thống không thể tự động tính toán giá trị thật cho các sensor này.
        ///Bạn có muốn cập nhật hệ số tính toán cho cáccảm biến ngay bây giờ không?.
        /// </summary>
        internal static string Confirm_UpdateSensorParamFirst {
            get {
                return ResourceManager.GetString("Confirm_UpdateSensorParamFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo lựa chọn.
        /// </summary>
        internal static string ConfirmMessageCaption {
            get {
                return ResourceManager.GetString("ConfirmMessageCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap correct_16 {
            get {
                object obj = ResourceManager.GetObject("correct_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_16 {
            get {
                object obj = ResourceManager.GetObject("disk_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_16 {
            get {
                object obj = ResourceManager.GetObject("folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước file: {0} bytes.
        /// </summary>
        internal static string Label_Logger_FileSize {
            get {
                return ResourceManager.GetString("Label_Logger_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi đầu: {0}.
        /// </summary>
        internal static string Label_Logger_FirstDate {
            get {
                return ResourceManager.GetString("Label_Logger_FirstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi cuối: {0}.
        /// </summary>
        internal static string Label_Logger_LastDate {
            get {
                return ResourceManager.GetString("Label_Logger_LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần đọc cuối: {0}.
        /// </summary>
        internal static string Label_Logger_LastModify {
            get {
                return ResourceManager.GetString("Label_Logger_LastModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta: {0}.
        /// </summary>
        internal static string Label_Logger_Meta {
            get {
                return ResourceManager.GetString("Label_Logger_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản ghi: {0}.
        /// </summary>
        internal static string Label_Logger_RecordCount {
            get {
                return ResourceManager.GetString("Label_Logger_RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cảm biến : {0}.
        /// </summary>
        internal static string Label_Logger_SensorCount {
            get {
                return ResourceManager.GetString("Label_Logger_SensorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đọc : {0}.
        /// </summary>
        internal static string Label_Logger_Status {
            get {
                return ResourceManager.GetString("Label_Logger_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa lần cuối: {0}.
        /// </summary>
        internal static string LastEditedDate {
            get {
                return ResourceManager.GetString("LastEditedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Logger mới.
        /// </summary>
        internal static string LoggersManagerForm_Add_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Add_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc toàn bộ File.
        /// </summary>
        internal static string LoggersManagerForm_AllFile {
            get {
                return ResourceManager.GetString("LoggersManagerForm_AllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bật chế độ tự đọc dữ liệu sau một khoảng thời gian (chỉ đọc các bản ghi mới).
        /// </summary>
        internal static string LoggersManagerForm_AutoRead_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_AutoRead_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc dữ liệu từ Logger bằng tay.
        /// </summary>
        internal static string LoggersManagerForm_Begin_Read {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Begin_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động đọc.
        /// </summary>
        internal static string LoggersManagerForm_Column_AutoRead {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Column_AutoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LoggersManagerForm_Column_ID {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string LoggersManagerForm_Column_Name {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn file data.
        /// </summary>
        internal static string LoggersManagerForm_Column_Path {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Column_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Logger đang chọn, đồng thời xóa dữ liệu cảm biến tương ứng với Logger này..
        /// </summary>
        internal static string LoggersManagerForm_Delete_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dấu phân cách.
        /// </summary>
        internal static string LoggersManagerForm_Delimiter {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dấu phân cách giữa các giá trị trong file dữ liêu.
        /// </summary>
        internal static string LoggersManagerForm_Delimiter_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Delimiter_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        internal static string LoggersManagerForm_EditSensor {
            get {
                return ResourceManager.GetString("LoggersManagerForm_EditSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa các cảm biến trong logger.
        /// </summary>
        internal static string LoggersManagerForm_EditSensor_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_EditSensor_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước file: {0} bytes.
        /// </summary>
        internal static string LoggersManagerForm_FileSize {
            get {
                return ResourceManager.GetString("LoggersManagerForm_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi đầu: {0}.
        /// </summary>
        internal static string LoggersManagerForm_FirstRecordDate {
            get {
                return ResourceManager.GetString("LoggersManagerForm_FirstRecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click đúp để sửa thông tin Logger.
        /// </summary>
        internal static string LoggersManagerForm_Grid_Hint {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Grid_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần đọc cuối: {0}.
        /// </summary>
        internal static string LoggersManagerForm_LastModifyDate {
            get {
                return ResourceManager.GetString("LoggersManagerForm_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi cuối: {0}.
        /// </summary>
        internal static string LoggersManagerForm_LastRecordDate {
            get {
                return ResourceManager.GetString("LoggersManagerForm_LastRecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Logger.
        /// </summary>
        internal static string LoggersManagerForm_LoggerName {
            get {
                return ResourceManager.GetString("LoggersManagerForm_LoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta: {0}.
        /// </summary>
        internal static string LoggersManagerForm_Meta {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ bản ghi mới.
        /// </summary>
        internal static string LoggersManagerForm_OnlyNew {
            get {
                return ResourceManager.GetString("LoggersManagerForm_OnlyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        internal static string LoggersManagerForm_Path {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu đọc.
        /// </summary>
        internal static string LoggersManagerForm_Read {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chu kỳ đọc(s).
        /// </summary>
        internal static string LoggersManagerForm_ReadInterval {
            get {
                return ResourceManager.GetString("LoggersManagerForm_ReadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đọc: {0}.
        /// </summary>
        internal static string LoggersManagerForm_ReadStatus {
            get {
                return ResourceManager.GetString("LoggersManagerForm_ReadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản ghi: {0}.
        /// </summary>
        internal static string LoggersManagerForm_RecordNumber {
            get {
                return ResourceManager.GetString("LoggersManagerForm_RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cảm biến : {0}.
        /// </summary>
        internal static string LoggersManagerForm_SensorNumber {
            get {
                return ResourceManager.GetString("LoggersManagerForm_SensorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Loggers.
        /// </summary>
        internal static string LoggersManagerForm_Title {
            get {
                return ResourceManager.GetString("LoggersManagerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Logger thành công!
        ///Trước khi bấm nút đọc dữ liệu, bạn cần nhập hệ số các sensors trước!.
        /// </summary>
        internal static string Message_AddLoggerSuccess {
            get {
                return ResourceManager.GetString("Message_AddLoggerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm cảm biến thành công!.
        /// </summary>
        internal static string Message_AddSensorSuccess {
            get {
                return ResourceManager.GetString("Message_AddSensorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu dữ liệu thành công.
        /// </summary>
        internal static string Message_BackupSuccess {
            get {
                return ResourceManager.GetString("Message_BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính toán thành công {0} cảm biến!.
        /// </summary>
        internal static string Message_CalculateSensorsSuccess {
            get {
                return ResourceManager.GetString("Message_CalculateSensorsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa logger {0} ?.
        /// </summary>
        internal static string Message_ConfirmDeleteLogger {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa logger thành công!.
        /// </summary>
        internal static string Message_DeleteLoggerSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteLoggerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công {0} cảm biến!.
        /// </summary>
        internal static string Message_DeleteSensorsSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteSensorsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        internal static string Message_EditLoggerSuccess {
            get {
                return ResourceManager.GetString("Message_EditLoggerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin Logger thành công!
        ///Để bắt đầu tiến trình tự động đọc dữ liệu của Logger bạn hãy bấm nút [Bắt đầu đọc] bên dưới..
        /// </summary>
        internal static string Message_EditLoggerSuccess1 {
            get {
                return ResourceManager.GetString("Message_EditLoggerSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin Logger thành công!
        ///Tiến tiến trình tự động đọc dữ liệu của Logger đã hủy bỏ..
        /// </summary>
        internal static string Message_EditLoggerSuccess2 {
            get {
                return ResourceManager.GetString("Message_EditLoggerSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin cảm biến thành công!.
        /// </summary>
        internal static string Message_EditSensorSuccess {
            get {
                return ResourceManager.GetString("Message_EditSensorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc dữ liệu thành công!.
        /// </summary>
        internal static string Message_ReadDataSuccess {
            get {
                return ResourceManager.GetString("Message_ReadDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi dữ liệu thành công.
        /// </summary>
        internal static string Message_RestoreSuccess {
            get {
                return ResourceManager.GetString("Message_RestoreSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap off_16 {
            get {
                object obj = ResourceManager.GetObject("off_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap on_16 {
            get {
                object obj = ResourceManager.GetObject("on_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại dữ liệu trên bảng.
        /// </summary>
        internal static string Refresh_Hint {
            get {
                return ResourceManager.GetString("Refresh_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại bảng.
        /// </summary>
        internal static string RefreshTable {
            get {
                return ResourceManager.GetString("RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý cảm biến.
        /// </summary>
        internal static string SensorManageForm_Title {
            get {
                return ResourceManager.GetString("SensorManageForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string SensorsManagerForm_Add {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính toán.
        /// </summary>
        internal static string SensorsManagerForm_CalcTab {
            get {
                return ResourceManager.GetString("SensorsManagerForm_CalcTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string SensorsManagerForm_Column_ID {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự cột.
        /// </summary>
        internal static string SensorsManagerForm_Column_Index {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Column_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string SensorsManagerForm_Column_InfoTab {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Column_InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cảm biến.
        /// </summary>
        internal static string SensorsManagerForm_Column_Name {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị đo.
        /// </summary>
        internal static string SensorsManagerForm_Column_Unit {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Column_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mô tả về cảm biến.
        /// </summary>
        internal static string SensorsManagerForm_Description {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string SensorsManagerForm_Edit {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bật cảnh báo cho cảm biến này.
        /// </summary>
        internal static string SensorsManagerForm_EnableAlarm {
            get {
                return ResourceManager.GetString("SensorsManagerForm_EnableAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự cột.
        /// </summary>
        internal static string SensorsManagerForm_Index {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string SensorsManagerForm_InfoTab {
            get {
                return ResourceManager.GetString("SensorsManagerForm_InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bật cảnh báo.
        /// </summary>
        internal static string SensorsManagerForm_InitializeComponent_AlarmEnabled {
            get {
                return ResourceManager.GetString("SensorsManagerForm_InitializeComponent_AlarmEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cảnh báo.
        /// </summary>
        internal static string SensorsManagerForm_InitializeComponent_AlarmRunning {
            get {
                return ResourceManager.GetString("SensorsManagerForm_InitializeComponent_AlarmRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức cảnh báo trên.
        /// </summary>
        internal static string SensorsManagerForm_MaxAlarm {
            get {
                return ResourceManager.GetString("SensorsManagerForm_MaxAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức cảnh báo dưới.
        /// </summary>
        internal static string SensorsManagerForm_MinAlarm {
            get {
                return ResourceManager.GetString("SensorsManagerForm_MinAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính toán lại.
        /// </summary>
        internal static string SensorsManagerForm_ReCalc {
            get {
                return ResourceManager.GetString("SensorsManagerForm_ReCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cảm biến.
        /// </summary>
        internal static string SensorsManagerForm_SensorName {
            get {
                return ResourceManager.GetString("SensorsManagerForm_SensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý cảm biến.
        /// </summary>
        internal static string SensorsManagerForm_Title {
            get {
                return ResourceManager.GetString("SensorsManagerForm_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap table_edit_16 {
            get {
                object obj = ResourceManager.GetObject("table_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap to_database_16 {
            get {
                object obj = ResourceManager.GetObject("to_database_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string ToolTip_Title {
            get {
                return ResourceManager.GetString("ToolTip_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap warning_16 {
            get {
                object obj = ResourceManager.GetObject("warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn bản ghi nào!.
        /// </summary>
        internal static string Warning_NoRecordSelected {
            get {
                return ResourceManager.GetString("Warning_NoRecordSelected", resourceCulture);
            }
        }
    }
}
