//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Alarm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Alarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ALARM {
            get {
                return ResourceManager.GetStream("ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        internal static string AlarmManagerForm_Column_CalcValue {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_CalcValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string AlarmManagerForm_Column_EndDate {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc cảnh báo (giá trị đo từ sensor đã về đúng ngưỡng quy định).
        /// </summary>
        internal static string AlarmManagerForm_Column_EndDate_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_EndDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string AlarmManagerForm_Column_IsEnded {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_IsEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa cuối.
        /// </summary>
        internal static string AlarmManagerForm_Column_LastEditedDate {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_LastEditedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa cuối.
        /// </summary>
        internal static string AlarmManagerForm_Column_LastEditedUSer {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_LastEditedUSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string AlarmManagerForm_Column_StartDate {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu cảnh báo (sensor đo được giá trị ngoài ngưỡng quy định).
        /// </summary>
        internal static string AlarmManagerForm_Column_StartDate_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_StartDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string AlarmManagerForm_Column_Title {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string AlarmManagerForm_Delete {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa các logs được chọn.
        /// </summary>
        internal static string AlarmManagerForm_Delete_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa / Xóa.
        /// </summary>
        internal static string AlarmManagerForm_EditBox_Title {
            get {
                return ResourceManager.GetString("AlarmManagerForm_EditBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kết thúc.
        /// </summary>
        internal static string AlarmManagerForm_Ended {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string AlarmManagerForm_FromDate {
            get {
                return ResourceManager.GetString("AlarmManagerForm_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string AlarmManagerForm_ID {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string AlarmManagerForm_Note {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ tìm kiếm.
        /// </summary>
        internal static string AlarmManagerForm_Refresh_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Refresh_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang diễn ra.
        /// </summary>
        internal static string AlarmManagerForm_Running {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string AlarmManagerForm_Save {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ghi chú.
        /// </summary>
        internal static string AlarmManagerForm_Save_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Save_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string AlarmManagerForm_Search {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        internal static string AlarmManagerForm_Sensor {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ xem alarm logs của sensor được chọn.
        /// </summary>
        internal static string AlarmManagerForm_Sensor_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Sensor_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cảm biến.
        /// </summary>
        internal static string AlarmManagerForm_Sensor_ID {
            get {
                return ResourceManager.GetString("AlarmManagerForm_Sensor_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string AlarmManagerForm_ToDate {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng ngày / tháng / năm - dd/MM/yyyy.
        /// </summary>
        internal static string AlarmManagerForm_ToDate_Hint {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ToDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem theo tùy chọn.
        /// </summary>
        internal static string AlarmManagerForm_ToDateTextBox {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ToDateTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string AlarmManagerForm_ToolTipTitle {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        internal static string AlarmManagerForm_UnSearch {
            get {
                return ResourceManager.GetString("AlarmManagerForm_UnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem theo tùy chọn.
        /// </summary>
        internal static string AlarmManagerForm_ViewBoxTitle {
            get {
                return ResourceManager.GetString("AlarmManagerForm_ViewBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} CẢM BIẾN ĐANG NGOÀI NGƯỠNG QUY ĐỊNH.
        /// </summary>
        internal static string AlarmNotifyForm_Title {
            get {
                return ResourceManager.GetString("AlarmNotifyForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bell_red_24 {
            get {
                object obj = ResourceManager.GetObject("bell_red_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bell_yellow_24 {
            get {
                object obj = ResourceManager.GetObject("bell_yellow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có xóa {0} alarm logs đã chọn không?.
        /// </summary>
        internal static string Confirm_DeleteLogs {
            get {
                return ResourceManager.GetString("Confirm_DeleteLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap correct_24 {
            get {
                object obj = ResourceManager.GetObject("correct_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_16 {
            get {
                object obj = ResourceManager.GetObject("disk_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công {0} alarm logs!.
        /// </summary>
        internal static string Message_DeleteLogsSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteLogsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ghi chú thành công!.
        /// </summary>
        internal static string Message_EditLogSuccess {
            get {
                return ResourceManager.GetString("Message_EditLogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhay_kieu_2 {
            get {
                object obj = ResourceManager.GetObject("nhay_kieu_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhay_kieu_3 {
            get {
                object obj = ResourceManager.GetObject("nhay_kieu_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_16 {
            get {
                object obj = ResourceManager.GetObject("search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn bản ghi nào!.
        /// </summary>
        internal static string Warning_NoRecordSelected {
            get {
                return ResourceManager.GetString("Warning_NoRecordSelected", resourceCulture);
            }
        }
    }
}
