//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Views.ChartView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Views.ChartView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_16 {
            get {
                object obj = ResourceManager.GetObject("calculator_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_view_32 {
            get {
                object obj = ResourceManager.GetObject("chart_view_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả cảm biến.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_All_Sensors {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_All_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả cảm biến.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_AllSensors {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_AllSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart View.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Chart_View {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Chart_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng lại.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Close {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Cutomize {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Cutomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vẽ chart.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Drawchart {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Drawchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Edit {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_File {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_From {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_FromDate {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Group {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Picture {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Print {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bản in.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Print_Preview {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Print_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart View.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_Title {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_To {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string ChartMainForm_InitializeComponent_ToDate {
            get {
                return ResourceManager.GetString("ChartMainForm_InitializeComponent_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart View.
        /// </summary>
        internal static string ChartViewForm_InitializeComponent_Title {
            get {
                return ResourceManager.GetString("ChartViewForm_InitializeComponent_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_16 {
            get {
                object obj = ResourceManager.GetObject("disk_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nét đậm.
        /// </summary>
        internal static string EditScaleForm_Bold_of_Line {
            get {
                return ResourceManager.GetString("EditScaleForm_Bold_of_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        internal static string EditScaleForm_Cancel {
            get {
                return ResourceManager.GetString("EditScaleForm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string EditScaleForm_Chart_Title {
            get {
                return ResourceManager.GetString("EditScaleForm_Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string EditScaleForm_ChartBox {
            get {
                return ResourceManager.GetString("EditScaleForm_ChartBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        internal static string EditScaleForm_Color {
            get {
                return ResourceManager.GetString("EditScaleForm_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditScaleForm_OK {
            get {
                return ResourceManager.GetString("EditScaleForm_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến hiển thị.
        /// </summary>
        internal static string EditScaleForm_SensorsBox {
            get {
                return ResourceManager.GetString("EditScaleForm_SensorsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh.
        /// </summary>
        internal static string EditScaleForm_Title {
            get {
                return ResourceManager.GetString("EditScaleForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu vẽ.
        /// </summary>
        internal static string EditScaleForm_Type_of_Data {
            get {
                return ResourceManager.GetString("EditScaleForm_Type_of_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trục X.
        /// </summary>
        internal static string EditScaleForm_XAxis_Title {
            get {
                return ResourceManager.GetString("EditScaleForm_XAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trục Y.
        /// </summary>
        internal static string EditScaleForm_YAxis_Title {
            get {
                return ResourceManager.GetString("EditScaleForm_YAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm.
        /// </summary>
        internal static string GroupCreate_InitializeComponent_Create {
            get {
                return ResourceManager.GetString("GroupCreate_InitializeComponent_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        internal static string GroupCreate_InitializeComponent_GroupName {
            get {
                return ResourceManager.GetString("GroupCreate_InitializeComponent_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm cảm biến mới.
        /// </summary>
        internal static string GroupCreate_InitializeComponent_Title {
            get {
                return ResourceManager.GetString("GroupCreate_InitializeComponent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_AddGroup {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm cảm biến.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_AddSensor {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_AddSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhóm.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_DeleteGroup {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ cảm biến.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_Remove_Sensor {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_Remove_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_Save {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cảm biến.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_SensorName {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_SensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến trong nhóm.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_Sensors {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhóm cảm biến hiển thị trên Chart View.
        /// </summary>
        internal static string GroupsManagerForm_InitializeComponent_Title {
            get {
                return ResourceManager.GetString("GroupsManagerForm_InitializeComponent_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap login_16 {
            get {
                object obj = ResourceManager.GetObject("login_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm thành công!.
        /// </summary>
        internal static string Message_CreateGroup_Success {
            get {
                return ResourceManager.GetString("Message_CreateGroup_Success", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
