//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoViewer.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoViewer.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo lựa chọn.
        /// </summary>
        internal static string ConfirmMessageCaption {
            get {
                return ResourceManager.GetString("ConfirmMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại!.
        /// </summary>
        internal static string Error_Account_AccountNotExist {
            get {
                return ResourceManager.GetString("Error_Account_AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại!.
        /// </summary>
        internal static string Error_Account_EmailExist {
            get {
                return ResourceManager.GetString("Error_Account_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng!.
        /// </summary>
        internal static string Error_Account_EmailIsUsed {
            get {
                return ResourceManager.GetString("Error_Account_EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa!.
        /// </summary>
        internal static string Error_Account_IsLocked {
            get {
                return ResourceManager.GetString("Error_Account_IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng!.
        /// </summary>
        internal static string Error_Account_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Error_Account_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được duyệt!.
        /// </summary>
        internal static string Error_Account_UnApproved {
            get {
                return ResourceManager.GetString("Error_Account_UnApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại!.
        /// </summary>
        internal static string Error_Account_UsernameExist {
            get {
                return ResourceManager.GetString("Error_Account_UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú không dài quá 500 ký tự!.
        /// </summary>
        internal static string Error_AlarmLogNoteInvalid {
            get {
                return ResourceManager.GetString("Error_AlarmLogNoteInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_AlarmLogTitleInvalid {
            get {
                return ResourceManager.GetString("Error_AlarmLogTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không tồn tại!.
        /// </summary>
        internal static string Error_BackupFileNotExist {
            get {
                return ResourceManager.GetString("Error_BackupFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến chưa nhập hệ số tính toán!.
        /// </summary>
        internal static string Error_Calculating_EmptyParam {
            get {
                return ResourceManager.GetString("Error_Calculating_EmptyParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa tài khoản RootAdmin!.
        /// </summary>
        internal static string Error_CannotDeleteRootAdmin {
            get {
                return ResourceManager.GetString("Error_CannotDeleteRootAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể khóa tài khoản RootAdmin!.
        /// </summary>
        internal static string Error_CannotLockRootAdmin {
            get {
                return ResourceManager.GetString("Error_CannotLockRootAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể bỏ quyền quản lý tài khoản của RootAdmin!.
        /// </summary>
        internal static string Error_CannotRemoveAccountRoleOfRootAdmin {
            get {
                return ResourceManager.GetString("Error_CannotRemoveAccountRoleOfRootAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File dữ liệu không tồn tại.
        /// </summary>
        internal static string Error_Data_FileNotFound {
            get {
                return ResourceManager.GetString("Error_Data_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File database không tồn tại!.
        /// </summary>
        internal static string Error_DatabaseNotExist {
            get {
                return ResourceManager.GetString("Error_DatabaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng!.
        /// </summary>
        internal static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không vượt quá 100 ký tự!.
        /// </summary>
        internal static string Error_FullNameInvalid {
            get {
                return ResourceManager.GetString("Error_FullNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_GroupNameInvalid {
            get {
                return ResourceManager.GetString("Error_GroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên logger không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_LoggerNameInvalid {
            get {
                return ResourceManager.GetString("Error_LoggerNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên picture view không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_NameNameInvalid {
            get {
                return ResourceManager.GetString("Error_NameNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng!.
        /// </summary>
        internal static string Error_OldPasswordNotMatch {
            get {
                return ResourceManager.GetString("Error_OldPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin picture view không dài quá 500 ký tự!.
        /// </summary>
        internal static string Error_PictureDescriptionInvalid {
            get {
                return ResourceManager.GetString("Error_PictureDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên picture view không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_PictureNameInvalid {
            get {
                return ResourceManager.GetString("Error_PictureNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện tác vụ này, hãy liên hệ với Admin để thêm quyền cho bạn!.
        /// </summary>
        internal static string Error_Security_NotPermission {
            get {
                return ResourceManager.GetString("Error_Security_NotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cảm biến không dài quá 500 ký tự!.
        /// </summary>
        internal static string Error_SensorDescriptionInvalid {
            get {
                return ResourceManager.GetString("Error_SensorDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cảm biến không được để trống và không dài quá 200 ký tự!.
        /// </summary>
        internal static string Error_SensorNameInvalid {
            get {
                return ResourceManager.GetString("Error_SensorNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cảnh báo không hợp lệ!.
        /// </summary>
        internal static string Error_SetAlarmInvalid {
            get {
                return ResourceManager.GetString("Error_SetAlarmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản không hợp lệ. Tài khoản hợp lệ chỉ gồm chữ cái, số dấu _ và có độ dài từ 4-20 ký tự!.
        /// </summary>
        internal static string Error_UsernameInvalid {
            get {
                return ResourceManager.GetString("Error_UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo lỗi.
        /// </summary>
        internal static string ErrorMessageCaption {
            get {
                return ResourceManager.GetString("ErrorMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đăng nhập!.
        /// </summary>
        internal static string SecurityBLL_MustLogin {
            get {
                return ResourceManager.GetString("SecurityBLL_MustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thành công.
        /// </summary>
        internal static string SuccessMessageCaption {
            get {
                return ResourceManager.GetString("SuccessMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string WarningMessageCaption {
            get {
                return ResourceManager.GetString("WarningMessageCaption", resourceCulture);
            }
        }
    }
}
