//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geoviewer.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geoviewer.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string AccountManagerForm_Account {
            get {
                return ResourceManager.GetString("AccountManagerForm_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản người dùng.
        /// </summary>
        internal static string AccountManagerForm_Account_Hint {
            get {
                return ResourceManager.GetString("AccountManagerForm_Account_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tài khoản.
        /// </summary>
        internal static string AccountManagerForm_AccountRole {
            get {
                return ResourceManager.GetString("AccountManagerForm_AccountRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm / Chỉnh sửa.
        /// </summary>
        internal static string AccountManagerForm_AddEdit {
            get {
                return ResourceManager.GetString("AccountManagerForm_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý cảnh báo(Thiết đặt, lịch sử cảnh báo).
        /// </summary>
        internal static string AccountManagerForm_AlarmRole {
            get {
                return ResourceManager.GetString("AccountManagerForm_AlarmRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        internal static string AccountManagerForm_Approved {
            get {
                return ResourceManager.GetString("AccountManagerForm_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string AccountManagerForm_CreatedDate {
            get {
                return ResourceManager.GetString("AccountManagerForm_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Data (Logger, cảm biến, sao lưu).
        /// </summary>
        internal static string AccountManagerForm_DataRole {
            get {
                return ResourceManager.GetString("AccountManagerForm_DataRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        internal static string AccountManagerForm_Email {
            get {
                return ResourceManager.GetString("AccountManagerForm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string AccountManagerForm_FullName {
            get {
                return ResourceManager.GetString("AccountManagerForm_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần đăng nhập cuối.
        /// </summary>
        internal static string AccountManagerForm_LastLoginDate {
            get {
                return ResourceManager.GetString("AccountManagerForm_LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa tài khoản.
        /// </summary>
        internal static string AccountManagerForm_Lock {
            get {
                return ResourceManager.GetString("AccountManagerForm_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị khóa.
        /// </summary>
        internal static string AccountManagerForm_Locked {
            get {
                return ResourceManager.GetString("AccountManagerForm_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string AccountManagerForm_Password {
            get {
                return ResourceManager.GetString("AccountManagerForm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mật khẩu.
        /// </summary>
        internal static string AccountManagerForm_ResetPass {
            get {
                return ResourceManager.GetString("AccountManagerForm_ResetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu cho người dùng.
        /// </summary>
        internal static string AccountManagerForm_ResetPass_Hint {
            get {
                return ResourceManager.GetString("AccountManagerForm_ResetPass_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string AccountManagerForm_Role {
            get {
                return ResourceManager.GetString("AccountManagerForm_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string AccountManagerForm_RoleEdit {
            get {
                return ResourceManager.GetString("AccountManagerForm_RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn quyền.
        /// </summary>
        internal static string AccountManagerForm_RoleManage {
            get {
                return ResourceManager.GetString("AccountManagerForm_RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem, in, báo cáo.
        /// </summary>
        internal static string AccountManagerForm_RoleView {
            get {
                return ResourceManager.GetString("AccountManagerForm_RoleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tài khoản người dùng.
        /// </summary>
        internal static string AccountManagerForm_Title {
            get {
                return ResourceManager.GetString("AccountManagerForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý View (Picture, Chart, Text View).
        /// </summary>
        internal static string AccountManagerForm_ViewRole {
            get {
                return ResourceManager.GetString("AccountManagerForm_ViewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_16 {
            get {
                object obj = ResourceManager.GetObject("disk_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới không đúng!.
        /// </summary>
        internal static string Error_ConfimPassNotMatch {
            get {
                return ResourceManager.GetString("Error_ConfimPassNotMatch", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap key_edit_16 {
            get {
                object obj = ResourceManager.GetObject("key_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công!.
        /// </summary>
        internal static string Message_AddAccountSuccess {
            get {
                return ResourceManager.GetString("Message_AddAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa tài khoản {0} ?.
        /// </summary>
        internal static string Message_ConfirmDeleteAccount {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa người dùng thành công!.
        /// </summary>
        internal static string Message_DeleteAccountSuccess {
            get {
                return ResourceManager.GetString("Message_DeleteAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        internal static string Message_EditAccountSuccess {
            get {
                return ResourceManager.GetString("Message_EditAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công!.
        /// </summary>
        internal static string Message_ResetPassSuccess {
            get {
                return ResourceManager.GetString("Message_ResetPassSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại bảng.
        /// </summary>
        internal static string RefreshTable {
            get {
                return ResourceManager.GetString("RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap table_edit_16 {
            get {
                object obj = ResourceManager.GetObject("table_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string Tooltip_Title {
            get {
                return ResourceManager.GetString("Tooltip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn bản ghi nào!.
        /// </summary>
        internal static string Warning_NoRecordSelected {
            get {
                return ResourceManager.GetString("Warning_NoRecordSelected", resourceCulture);
            }
        }
    }
}
